// Copyright (c) 2025 hotflow2024
// Licensed under AGPL-3.0-or-later. See LICENSE for details.
// Commercial licensing available. See COMMERCIAL_LICENSE.md.

/**
 * Script → Blueprint conversion.
 *
 * Converts `ScriptProjectData.shots` (Shot[]) into blueprint node groups.
 * Each shot becomes a set of connected nodes:
 *   text-input (prompt) → image-generator → output
n *   script-import (context) → image-generator
 *
 * Supports creating preview from selected shots or the full shot list.
 *
 * ── Generation Chain Boundary (§9.3) ─────────────────────────────
 * This module reads from `Shot` types (script domain), NOT from
 * Director's `SplitScene` or S-Class's `ShotGroup`. If Director
 * data import is needed, create a separate `director-to-blueprint.ts`
 * adapter that maps SplitScene fields to blueprint nodes — do not
 * import director-store or sclass-store here.
 *
 * Storyboard grid images, joint images, and scene splitting are
 * Director/S-Class features and must NOT be replicated in blueprint.
 * ─────────────────────────────────────────────────────────────────
 */

import type {
  BlueprintNode,
  BlueprintEdge,
  BlueprintProject,
  BlueprintSourceRef,
  BlueprintImageGeneratorConfig,
  TextInputNodeConfig,
  ScriptImportNodeConfig,
  OutputNodeConfig,
  MediaReferenceNodeConfig,
} from '@/types/blueprint';
import type { Shot } from '@/types/script';
import { BLUEPRINT_SCHEMA_VERSION } from '@/types/blueprint';
import { generateUUID } from '@/lib/utils';
import type { BlueprintDiagnostic } from './graph-validation';
import { parseMarkdownScript, scenesToShots } from './markdown-script-parser';

// ── Types ─────────────────────────────────────────────────────────────────

export interface ConvertScriptToBlueprintOptions {
  /** Target project ID for the blueprint. */
  projectId: string;
  /**
   * Script project data containing shots.
   * When provided along with `rawScript`, shots are used directly.
   * When only `rawScript` is provided, shots are generated by parsing
   * the Markdown content.
   */
  shots?: Shot[];
  /**
   * Raw Markdown script content. When `shots` is empty or not provided,
   * this content is parsed to generate shots automatically.
   * When `shots` is also provided, this is used for source version tracking.
   */
  rawScript?: string;
  /**
   * ScriptProjectData for full context. If provided and `shots` is omitted,
   * `scriptProjectData.shots` is used.
   */
  scriptProjectData?: { shots: Shot[]; rawScript?: string; updatedAt?: number };
  /**
   * Which shots to include. When omitted, all shots are converted.
   * When provided, only the specified shot IDs are included.
   */
  selectedShotIds?: string[];
  /**
   * Conversion mode:
   * - 'full': creates a complete blueprint with all selected shots.
   * - 'preview': creates a lightweight preview (useful for diff/confirmation UI).
   */
  mode?: 'full' | 'preview';
  /** Optional blueprint name override. */
  name?: string;
  /** Existing blueprint ID to update (for re-import). */
  existingBlueprintId?: string;
}

export interface ScriptToBlueprintResult {
  /** The generated blueprint project. */
  blueprint: BlueprintProject;
  /** Number of shots converted. */
  shotCount: number;
  /** Number of nodes created. */
  nodeCount: number;
  /** Number of edges created. */
  edgeCount: number;
  /** Shot IDs that were included. */
  includedShotIds: string[];
  /**
   * Diagnostics generated during conversion.
   * Includes warnings for shots without prompts, missing assets,
   * and stale source references.
   */
  diagnostics: BlueprintDiagnostic[];
}

// ── Helpers ───────────────────────────────────────────────────────────────

/** Pick the best available prompt from a shot. */
function resolveShotPrompt(shot: Shot): string {
  // Prefer structured prompts, fall back to visual description
  return shot.imagePrompt
    || shot.visualPrompt
    || shot.visualDescription
    || shot.actionSummary
    || '';
}

/** Build a source reference for a shot. */
function makeShotSourceRef(
  shot: Shot,
  sourceVersion?: string,
): BlueprintSourceRef {
  return {
    kind: 'shot',
    id: shot.id,
    sourceVersion,
  };
}

/**
 * Generate diagnostics for the given shots.
 * Reports missing prompts, missing character references, and other issues.
 */
function generateConversionDiagnostics(
  shots: Shot[],
  includedShotIds: string[],
): BlueprintDiagnostic[] {
  const diagnostics: BlueprintDiagnostic[] = [];

  for (const shotId of includedShotIds) {
    const shot = shots.find((s) => s.id === shotId);
    if (!shot) continue;

    const prompt = resolveShotPrompt(shot);
    if (!prompt) {
      diagnostics.push({
        code: 'shot-missing-prompt',
        severity: 'warning',
        message: `镜头 ${shot.index + 1} (ID: ${shot.id}) 没有可用的提示词。仅生成 script-import 节点，不创建生成器。`,
      });
    }

    if (shot.characterIds.length > 0 && (!shot.characterNames || shot.characterNames.length === 0)) {
      diagnostics.push({
        code: 'shot-missing-character-names',
        severity: 'info',
        message: `镜头 ${shot.index + 1} (ID: ${shot.id}) 有角色 ID 但缺少角色名称。`,
      });
    }
  }

  return diagnostics;
}

// ── Main conversion ───────────────────────────────────────────────────────

/**
 * Convert script shots into a blueprint graph.
 *
 * Each shot generates a node group:
 * 1. `text-input` — the shot's image/video prompt
 * 2. `script-import` — context reference linking back to the shot
 * 3. `image-generator` — connects to text-input + script-import
 * 4. `output` — collects the generated image
 *
 * When a shot has no usable prompt, only a script-import node is created
 * (no generator or output), and the shot is still tracked in the result.
 */
export function convertScriptToBlueprint(
  options: ConvertScriptToBlueprintOptions,
): ScriptToBlueprintResult {
  const {
    projectId,
    selectedShotIds,
    mode = 'full',
    name,
    existingBlueprintId,
    scriptProjectData,
    rawScript,
  } = options;

  // Resolve shots from available sources:
  // 1. Explicit shots option
  // 2. scriptProjectData.shots
  // 3. Parse from rawScript (Markdown)
  let resolvedShots = options.shots ?? scriptProjectData?.shots ?? [];
  const resolvedRawScript = rawScript ?? scriptProjectData?.rawScript ?? '';

  if (resolvedShots.length === 0 && resolvedRawScript) {
    // Parse Markdown to generate shots
    const parseResult = parseMarkdownScript(resolvedRawScript);
    resolvedShots = scenesToShots(parseResult);
  }

  // Compute source version from script timestamp or content hash
  const sourceVersion = scriptProjectData?.updatedAt
    ? String(scriptProjectData.updatedAt)
    : resolvedRawScript
      ? String(resolvedRawScript.length)
      : undefined;

  // Filter shots
  const targetShots = selectedShotIds && selectedShotIds.length > 0
    ? resolvedShots.filter((s) => selectedShotIds.includes(s.id))
    : resolvedShots;

  const nodes: BlueprintNode[] = [];
  const edges: BlueprintEdge[] = [];
  const includedShotIds: string[] = [];

  // Track positions for auto-layout
  let yOffset = 0;
  const X_SPACING = 320;
  const Y_SPACING = 200;

  for (const shot of targetShots) {
    const prompt = resolveShotPrompt(shot);
    const sourceRef = makeShotSourceRef(shot, sourceVersion);

    // 1. Text-input node for the prompt
    const textInputId = generateUUID();
    const textConfig: TextInputNodeConfig = { text: prompt };
    nodes.push({
      id: textInputId,
      type: 'text-input',
      position: { x: 0, y: yOffset },
      data: {
        nodeType: 'text-input',
        label: `镜头 ${shot.index + 1} 提示词`,
        config: textConfig,
        sourceRef,
      },
    });

    // 2. Script-import node for context
    const scriptImportId = generateUUID();
    const importConfig: ScriptImportNodeConfig = {
      selectedShotIds: [shot.id],
      mode: 'snapshot',
    };
    nodes.push({
      id: scriptImportId,
      type: 'script-import',
      position: { x: 0, y: yOffset + Y_SPACING * 0.5 },
      data: {
        nodeType: 'script-import',
        label: `镜头 ${shot.index + 1} 剧本`,
        config: importConfig,
        sourceRef,
      },
    });

    if (prompt) {
      // 3. Image-generator node
      const generatorId = generateUUID();
      const genConfig: BlueprintImageGeneratorConfig = {
        prompt: '',
      };
      nodes.push({
        id: generatorId,
        type: 'image-generator',
        position: { x: X_SPACING, y: yOffset },
        data: {
          nodeType: 'image-generator',
          label: `镜头 ${shot.index + 1} 生成`,
          config: genConfig,
          sourceRef,
        },
      });

      // 4. Output node
      const outputId = generateUUID();
      const outConfig: OutputNodeConfig = {
        acceptedTypes: ['image'],
      };
      nodes.push({
        id: outputId,
        type: 'output',
        position: { x: X_SPACING * 2, y: yOffset },
        data: {
          nodeType: 'output',
          label: `镜头 ${shot.index + 1} 输出`,
          config: outConfig,
          sourceRef,
        },
      });

      // Edges: text-input → image-generator (prompt port)
      edges.push({
        id: generateUUID(),
        source: textInputId,
        target: generatorId,
        sourceHandle: 'text',
        targetHandle: 'prompt',
        type: 'blueprint',
        data: { dataType: 'text' },
      });

      // Edges: script-import → image-generator (prompt port, for context)
      edges.push({
        id: generateUUID(),
        source: scriptImportId,
        target: generatorId,
        sourceHandle: 'context',
        targetHandle: 'prompt',
        type: 'blueprint',
        data: { dataType: 'context' },
      });

      // Edges: image-generator → output
      edges.push({
        id: generateUUID(),
        source: generatorId,
        target: outputId,
        sourceHandle: 'image',
        targetHandle: 'media',
        type: 'blueprint',
        data: { dataType: 'image' },
      });
    }

    includedShotIds.push(shot.id);
    yOffset += Y_SPACING;
  }

  const blueprintId = existingBlueprintId ?? generateUUID();
  const blueprintName = name ?? `剧本导入 ${new Date().toLocaleDateString('zh-CN')}`;

  const blueprint: BlueprintProject = {
    id: blueprintId,
    projectId,
    name: blueprintName,
    version: BLUEPRINT_SCHEMA_VERSION,
    nodes,
    edges,
    viewport: { x: 0, y: 0, zoom: 1 },
    status: 'draft',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  // Generate diagnostics
  const diagnostics = generateConversionDiagnostics(resolvedShots, includedShotIds);

  return {
    blueprint,
    shotCount: includedShotIds.length,
    nodeCount: nodes.length,
    edgeCount: edges.length,
    includedShotIds,
    diagnostics,
  };
}

/**
 * Create a lightweight preview of what the blueprint would look like.
 * Same as `convertScriptToBlueprint` with `mode: 'preview'` but returns
 * only summary info without the full node graph (useful for UI diff).
 */
export function previewScriptToBlueprint(
  options: Omit<ConvertScriptToBlueprintOptions, 'mode'>,
): { shotCount: number; nodeCount: number; hasPrompts: number; missingPrompts: number; diagnostics: BlueprintDiagnostic[] } {
  // Resolve shots from available sources
  const resolvedShots = options.shots
    ?? options.scriptProjectData?.shots
    ?? (options.rawScript
      ? scenesToShots(parseMarkdownScript(options.rawScript))
      : []);

  const targetShots = options.selectedShotIds && options.selectedShotIds.length > 0
    ? resolvedShots.filter((s) => options.selectedShotIds!.includes(s.id))
    : resolvedShots;

  let hasPrompts = 0;
  let missingPrompts = 0;

  for (const shot of targetShots) {
    if (resolveShotPrompt(shot)) {
      hasPrompts++;
    } else {
      missingPrompts++;
    }
  }

  // Each shot with a prompt generates 4 nodes; without prompt, 2 nodes
  const nodeCount = hasPrompts * 4 + missingPrompts * 2;

  // Generate diagnostics for preview
  const diagnostics = generateConversionDiagnostics(
    resolvedShots,
    targetShots.map((s) => s.id),
  );

  return {
    shotCount: targetShots.length,
    nodeCount,
    hasPrompts,
    missingPrompts,
    diagnostics,
  };
}
